// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1u-4JxJO6-WF9sA92PTYCJtQGCAdwJ98',
    appId: '1:781555734480:web:80c1e8e12f4b0f846c8bd5',
    messagingSenderId: '781555734480',
    projectId: 'blood-donation-28e5c',
    authDomain: 'blood-donation-28e5c.firebaseapp.com',
    databaseURL: 'https://blood-donation-28e5c-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-28e5c.appspot.com',
    measurementId: 'G-KD6KFV2ZPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1IlzxEfv6km5Ji37Cy-7nhG2jbzU28_U',
    appId: '1:781555734480:android:38f9f6bd3935b76f6c8bd5',
    messagingSenderId: '781555734480',
    projectId: 'blood-donation-28e5c',
    databaseURL: 'https://blood-donation-28e5c-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-28e5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHwFKygacvWjx-bYgcQ6AXDmcBc1so6Q0',
    appId: '1:781555734480:ios:2f4200c0914a9b0b6c8bd5',
    messagingSenderId: '781555734480',
    projectId: 'blood-donation-28e5c',
    databaseURL: 'https://blood-donation-28e5c-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-28e5c.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHwFKygacvWjx-bYgcQ6AXDmcBc1so6Q0',
    appId: '1:781555734480:ios:2f4200c0914a9b0b6c8bd5',
    messagingSenderId: '781555734480',
    projectId: 'blood-donation-28e5c',
    databaseURL: 'https://blood-donation-28e5c-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-28e5c.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
